/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.48
 * Generated at: 2021-09-28 15:01:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=240\"/>\r\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("	<meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\" />\r\n");
      out.write("	<meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n");
      out.write("	<meta http-equiv=\"Expires\" content=\"0\" />\r\n");
      out.write("	<META HTTP-Equiv=\"scanner\" Content=\"disabled\">\r\n");
      out.write("	<META HTTP-Equiv=\"scanner\" Content=\"autoenter\">\r\n");
      out.write("	<META HTTP-Equiv=\"acceleratekey\" content=\"all\">\r\n");
      out.write("	<META HTTP-Equiv=\"quitbutton\" Content=\"show\">\r\n");
      out.write("	<META HTTP-Equiv=\"quitbutton\" Content=\"x=0\">\r\n");
      out.write("	<META HTTP-Equiv=\"quitbutton\" Content=\"y=300\">\r\n");
      out.write("	<META HTTP-Equiv=\"battery\" Content=\"show\">\r\n");
      out.write("	<META HTTP-Equiv=\"battery\" Content=\"Bottom_GrowFromRight\">\r\n");
      out.write("	<META HTTP-Equiv=\"battery\" Content=\"RGB:FF,00,00\">   \r\n");
      out.write("	<META HTTP-Equiv=\"signal\" Content=\"show\">\r\n");
      out.write("	<META HTTP-Equiv=\"signal\" Content=\"Bottom_GrowFromRight\">\r\n");
      out.write("	<META HTTP-Equiv=\"signal\" Content=\"RGB:FF,00,00\">\r\n");
      out.write("	<META http-equiv=\"Volume\" content=\"SetVolume:0xFFFF\">\r\n");
      out.write("	<META HTTP-Equiv=\"wake\" Content=\"wakeLock:Enabled;wifiLock:Enabled\">\r\n");
      out.write("	<META HTTP-Equiv=\"unattended\" content=\"enabled\">\r\n");
      out.write("	\r\n");
      out.write("	<title>Welcome</title>\r\n");
      out.write("	<link href=\"style/commander.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body  onLoad = \"focusIt()\">\r\n");
      out.write("<form id=\"index\" name=\"index\" action=\"Process\" method=\"POST\">\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"238\">\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"100%\" height=\"20\" align=\"center\" style=\"height: 30px\">\r\n");
      out.write("		<p align=\"center\"><span class=\"splashTitleCommander\">Commander</span><span\r\n");
      out.write("			class=\"splashTitle4J\">4j</span></p>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td align=\"center\" style=\"height: 50px\" class=\"splashTitleVersion\">\r\n");
      out.write("		Version : ");
      out.print(com.commander4j.app.JVersion.getProgramVersion() );
      out.write("</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><img src=\"./images/splash.gif\" width=\"150\" style=\"display:block; margin-left:auto; margin-right:auto;\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td align=\"center\" style=\"height: 25px\" class=\"splashTitleVersion\">\r\n");
      out.write("		<small>Host : ");
      out.print(com.commander4j.bean.JServerName.getServername() );
      out.write("</small>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<td>&nbsp;</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td align=\"center\" style=\"height: 25px\">\r\n");
      out.write("			<input type=\"submit\" name=\"buttonStart\"	id=\"buttonStart\" value=\"Start\" 	onclick=\"document.index.button.value='Start';\">\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<input type=\"hidden\" name=\"formName\" value=\"index.jsp\" />\r\n");
      out.write("<input type=\"hidden\" id=\"button\" name=\"button\" value=\"Start\" /> \r\n");
      out.write("\r\n");
      out.write("</form> \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function focusIt()\r\n");
      out.write("{\r\n");
      out.write("	document.index.buttonStart.focus();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
